### ISSUE TITLE
Experiment started timestamp updates on re-render

### ISSUE THREAD

**Issue by calebsheridan** [dezoito/ollama-grid-search#10]
The timestamp for Experiment started uses new Date() in the render function which incorrectly updates the start time on re-renders.

The start time should not update on re-renders.

Recreate this issue by starting an experiment, waiting a few seconds, then pressing one of the Expand buttons which updates state and re-renders the date.

**Comment by dezoito** [comment]
Thank you!
Adding that to the list of changes for the next release.

**Comment by dezoito** [comment]
Fixed as of v0.4.0
