### ISSUE TITLE
Enable/disable parameters and their dependancies

### ISSUE THREAD

**Issue by calebsheridan** [dezoito/ollama-grid-search#13]
Suggestion for UX:

1. Allow parameters to be explicitly disabled (which results in using their default values, regardless of the input value).
2. If there are dependant parameters (e.g.: Mirostat must be enabled for Mirostat-Tau and Mirostat-Eta), the dependant parameters respect the parent's status.
~~3. Promote System Prompt from Settings Modal to Form Grid (it is the only parameter in Settings). By default, disable system prompt.~~

Disabled params will appear gray and only display on one line:

```
<title> <tooltip> <toggle>
```

Enabling params will appear normal and display on three lines:

```
<title> <tooltip> <toggle>
<input>
<explanation>
```

**Comment by dezoito** [comment]
Thank you for the suggestions.

I'll definitely consider #3 first, as it's the less messy to implement.
To disable the system prompt all you have to do is to leave it empty.

**Comment by calebsheridan** [comment]
If the suggestions are ok, we can leave the issue open until someone can work on it

**Comment by dezoito** [comment]
Done.

**Comment by dezoito** [comment]
@calebsheridan 

System prompt promoted to main form as of v0.4.0 (plus the changes you submitted and other minor updates)

Thank you for the input and PRs.
