### ISSUE TITLE
Latest release fails to run with: “ollama-grid-search” is damaged and can’t be opened

### ISSUE THREAD

**Issue by sammcj** [dezoito/ollama-grid-search#16]
1. Download the latest aarch64 dmg from releases.
2. Copy to /Applications
3. Open the application
4. Get error

<img width="261" alt="image" src="https://github.com/dezoito/ollama-grid-search/assets/862951/9dab895b-8825-463f-8bd9-aab2e925c68e">

**Comment by sammcj** [comment]
A workaround seems to be to remove all extended attributes from the App:

```
xattr -rc ollama-grid-search.app
```

**Comment by dezoito** [comment]
Can you try the x64 release?

https://github.com/dezoito/ollama-grid-search/releases/download/v0.4.1/ollama-grid-search_0.4.1_x64.dmg

Unfortunately, I merely use the GitHub action provided by the framework, and have no way to address this 

The aarch64 release showed up as a surprise this weekend too!

**Comment by sammcj** [comment]
The x64 release works (but have to right click -> open, accept its unsigned etc...) - but it's an intel binary, not an ARM (aarch64) binary so it runs in emulation.

<img width="863" alt="image" src="https://github.com/dezoito/ollama-grid-search/assets/862951/0255fc1e-811f-4f99-8ceb-b8fb546c0843">

**Comment by dezoito** [comment]
Any other Apple users having issues with the aarch64 dmg?

More importantly, anyone who knows what they are doing can suggest a way to fix it? :)

**Comment by sammcj** [comment]
@dezoito this _might_ fix it - https://github.com/dezoito/ollama-grid-search/pull/19

**Comment by dezoito** [comment]
Awesome work, sir!

**Comment by manasimi** [comment]
Hi I am still facing this issue, even with the latest release. Any reason why?

**Comment by dezoito** [comment]
> Hi I am still facing this issue, even with the latest release. Any reason why?

Hard to tell without specs (or me even having an ARC Mac)... I can only suggest you try a complete removal of the previous version before installing the latest, or try the x64 installer and run it in emulation.
