### ISSUE TITLE
error:llama runner process no longer running: 1 error:failed to create context with model

### ISSUE THREAD

**Issue by niyaz006** [dezoito/ollama-grid-search#17]
Facing the below error after I install and try for the first time. Are there are any other pre-requisites?

Windows
Models: Mixtral and Openhermes

`String error: An error occurred with ollama-rs: {"error":"llama runner process no longer running: 1 error:failed to create context with model 'C:\\Users\\<Username>\\.ollama\\models\\blobs\\sha256-671d85d606174999e3a99eb20534a120d0564ad2db3c38f04b7932beb021a687'"}`

**Comment by dezoito** [comment]
According to the error message, it seems that Ollama was not properly running on your machine.

**Comment by niyaz006** [comment]
Ollama works fine on PowerShell. And also through Python code in VSCode

**Comment by dezoito** [comment]
1- Is this a fresh install, or did you have a previous version installed?

2- Was there any change to the server URL config? Does it match the one you have working with Python?

**Comment by niyaz006** [comment]
I tried the url in browser and it says ollama is running.

Yes, my code in python still works

**Comment by dezoito** [comment]
I've searched on the Ollama repository and it seems that I'll itself is having issues with Windows (hopefully solved in the next release). 

Please see:

https://github.com/ollama/ollama/pull/3850
