### ISSUE TITLE
Choose other parameters?

### ISSUE THREAD

**Issue by boxabirds** [dezoito/ollama-grid-search#3]
This is a very helpful tool! Is there a way to experiment with other values other than temp,repeat penalty, top_k and top_p? 

Such as `repeat_last_n` -- default value of which seems not to work very well when handling conversation history.

**Comment by dezoito** [comment]
Implemented on v0.0.2.

@boxabirds, I'm closing this for now but please let me know if this works for you.

**Comment by dezoito** [comment]
Just as an FYI, v 0.2.1 supports user input for adicional parameters: tfs_z, mirostat, mirostat_eta and mirostat_tau.
