### ISSUE TITLE
Install ollama-grid-search as a module

### ISSUE THREAD

**Issue by NEWbie0709** [dezoito/ollama-grid-search#33]
I would like to install ollama-grid-search as a module in my main application. Could you please provide guidance or steps on how to achieve this?

**Comment by dezoito** [comment]
I don't think so.

**Comment by NEWbie0709** [comment]
Can we use a command line to run the program and get the result, or we can only install it as an application and use it?

**Comment by dezoito** [comment]
I like the idea, but for now it's only a standalone application.. if you call it from a command line you can see the "results" logged to the terminal (mostly left for debugging purposes), but there's no way to set the input arguments.

If you know Rust and you want something to get you started in that direction, please take a look at the old cli version:

https://github.com/dezoito/ollama-grid-search/tree/main/old

**Comment by NEWbie0709** [comment]
Alright, thanks for answering!
