### ISSUE TITLE
AppImage shows a blank screen then closes while the deb package works fine

### ISSUE THREAD

**Issue by LFd3v** [dezoito/ollama-grid-search#35]
Hey, there.

Thank you for developing and maintaining this nice app.

This is more a heads up than a bug report, since it seems that the problem only happens with the AppImage. After downloading the file, making it executable and trying to run the AppImage, it starts, shows a black window for a short time then closes (the same happened with the previous version - 0.5.0 - as well by the way):

```
$ ./ollama-grid-search_0.5.1_amd64.AppImage'
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
[1]    431463 segmentation fault (core dumped)  './ollama-grid-search_0.5.1_amd64.AppImage'
```

I am running Arch/Garuda, with GNOME on Wayland. I then used `debtap` to convert the deb package to an Arch package, as it seems this looks like a "self contained app" (Tauri or something like this?) and it worked just fine.

The closest thing I have found online to this bug is [this](https://github.com/tauri-apps/tauri/issues/4315), but using the suggested environment variable did not work for me. Also, using `G_MESSAGES_DEBUG=all` did not helped much, at least for me. I hope this helps debugging the issue somehow.

Thanks again. Regards.

**Comment by dezoito** [comment]
Thank you for the heads up.

This is more a Tauri issue, based on these results:

https://github.com/tauri-apps/tauri/issues/4315
https://github.com/tauri-apps/tauri/discussions/7879 


Adding  `WEBKIT_DISABLE_COMPOSITING_MODE=1` seemed to fix it in some of the comments above.

**Comment by LFd3v** [comment]
> Adding `WEBKIT_DISABLE_COMPOSITING_MODE=1` seemed to fix it in some of the comments above.

> >  but using the suggested environment variable did not work for me.

And it happens only with the AppImage. Anyway, thanks for your reply. Regards.
