### ISSUE TITLE
Read-only file system (os error 30) on MacOS

### ISSUE THREAD

**Issue by easp** [dezoito/ollama-grid-search#4]
I just tried ollama-grid-search for the first time. I'm using MacOS 14.4 and I'm using v0.1.0 of Ollama Grid Search.

For each permutation it takes a while, during which ollama keeps my GPU busy, and then displays: 
`Read-only file system (os error 30)` before moving on to the next permutation. It doesn't display the results of the inferences, just the error messages.

I can't tell where it is trying to write, but on MacOS, the root of the filesystem (/) is read only

**Comment by PieBru** [comment]
Nice tool!
Same here on Arch Linux using the .AppImage from a directory that contains all my AppImages. 
Thank you,
Piero

**Comment by easp** [comment]
@dezoito  Thanks

On MacOS, applications are typically added to /Applications, which seems writable, but the OS may be protecting to some degree. In any case though, not a great place to store data :)

By Apple's guidelines, most persistent, user-specific data that the user isn't expected to interact with outside of your app should be stored in an application specific directory in ~/Library/Application. The application specific subdirectory can just be the same as the name of your application bundle, though I think there is a more rigorous convention that is less likely to have collisions.

Data that the user might expect to use independently of your application should go into an app-specific or user chosen subdirectory in ~/Documents. For example, if your app generates text or json files with the results of a grid search that the user might want to use elsewhere.

Temp files should go in /tmp. There is an API for getting a unique, runtime-specific subdirectory.

Apple's documentation on the matter:
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW14

Often cross platform apps don't honor any of this and instead create an application specific directory in ~/. This is often prefixed by a period (ie .ollama-grid-search) so that it is hidden under ordinary circumstances.

**Comment by dezoito** [comment]
@easp , @PieBru,

I tested each release installer for each platform and they all worked, but the only Mac I have available is still using MacOS 12.7.

Could you guys give this another and check if it now works for you as well?

**Comment by dezoito** [comment]
> On MacOS, applications are typically added to /Applications, which seems writable, but the OS may be protecting to some degree. In any case though, not a great place to store data :)

Yes, I was trying to save to a folder relative to the binary, regrettably.

Tauri has an API dedicated to storing application files, but understanding how it works wasn't very straight forward.

In case anyone else developing a Tauri app sees this, this is the issue that eventually helped me:

https://github.com/tauri-apps/tauri/discussions/5557

Again, I appreciate the effort in testing the app and helping me sort this issue.

**Comment by PieBru** [comment]
No more errors now.
With only one model selected and more than one values in one or more params lists, I would expect more than one test will be performed, one for each "grid" of params. Instead:
![image](https://github.com/dezoito/ollama-grid-search/assets/6537434/0728857f-88d9-450a-94b6-6bc008961887)

**Comment by dezoito** [comment]
You just discovered an input validation bug, thank you!

Try separating values by commas, please.

**Comment by PieBru** [comment]
I did it with commas this morning, it works with commas.
Thank you!

**Comment by dezoito** [comment]
Fixed the issue that was allowing space delimited lists to pass parameter validation.

(added a few discreet UI tweaks as well).

Closing this issue, but please LMK if any problems persist
