### ISSUE TITLE
Crowdstrike finding: Malicious file nsis_tauri_utils.dll

### ISSUE THREAD

**Issue by awaescher** [dezoito/ollama-grid-search#43]
First of all: Thanks for the tool, I really like it a lot.

But let me get this feedback: I was just contacted by our administrators that the setup `ollama-grid-search_0.5.1_x64-setup.exe` caused a Crowdstrike finding: 

> Filename: nsis_tauri_utils.dll
> Finding: Win/malicious_confidence_70%

I found that this is from an  [open source NSIS plugin](https://github.com/tauri-apps/nsis-tauri-utils). They already have a thread about anti virus findings:
 - https://github.com/tauri-apps/nsis-tauri-utils/issues/37

It seems their newer version 0.4.1 passes the anti virus scans. It might be a good idea to check if you can rebuild your setup with this newer version. For me personally, this is not urgent - my app is running fine. Thanks once again.

**Comment by dezoito** [comment]
Hey there!

Thank you for the heads up (and the kind words)... This seems to be an issue with one of the Tauri plugins  used to build the releases and, unfortunately, there is nothing I can do on my end.

I checked the link you posted and I can see that FabianLars is already aware of the issue.
I'm not sure if I'll need to update any packages here (the entire build pipeline runs on a GitHub action), but if so I'll do it and publish a new release.
