### ISSUE TITLE
OGS turns off logging - is there a way to fix this?

### ISSUE THREAD

**Issue by zedmango** [dezoito/ollama-grid-search#6]
Looking through the logs at server.log I find this:

```time=2024-04-16T19:42:38.623-07:00 level=INFO source=server.go:264 msg="starting llama server" cmd="C:\\Users\\J\\AppData\\Local\\Temp\\ollama2950239959\\runners\\cuda_v11.3\\ollama_llama_server.exe --model C:\\Users\\J\\.ollama\\models\\blobs\\sha256-aa44bfe80b3d9cc9dbb32cb700e29fd3918f24d80693f27dd7dfda5cb68476d5 --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 0 --port 62547"```

Looks like OGS is adding a `--log-disable` option - I would like logging on. How do I fix this?

**Comment by dezoito** [comment]
That's set on your server.

AFAIK, clients have no way to set that,as that parameter is not even available in the REST API.

**Comment by zedmango** [comment]
Someone pointed me to this

https://github.com/ollama/ollama/blob/8d1995c625e7f2ed2ff98eb099e1bd8d7e6e133e/llm/server.go#L204-L208

looks like this can be done through the environmental variable OLLAMA_DEBUG.

**Comment by dezoito** [comment]
You probably know this, but just for the sake of someone searching for a similar issue, this is something set on the server side.
